apiVersion: v1
kind: Service
metadata:
      name: amazon-service
spec:
   selector:
      app: amazon
   ports:
      - name: port-1
        protocol: TCP
        port: 80
        targetPort: 80
      
