apiVersion: v1
kind: Service
metadata:
   name: flipkart-service
spec:
   type: NodePort
   selector:
      app: flipkart
   ports:
      - protocol: TCP
        port: 80
        targetPort: 80
        nodePort: 30001
~
